# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namePrefix: dev-codeblue-

namespace: codeblue

patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: ingress

images:
  - name: codeblue
    newName: jmalloc/echo-server
    # newTag: latest