# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeblue-web
  template:
    metadata:
      labels:
        app: codeblue-web
    spec:
      containers:
        - name: codeblue-web
          image: codeblue:latest
          ports:
            - containerPort: 8080
          livenessProbe:
              httpGet:
                path: /login
                port: 8080
                httpHeaders:
                  - name: Header-From-Pod
                    value: Awesome
              initialDelaySeconds: 3
              periodSeconds: 3
          resources:
            requests:
              memory: "50Mi"
              cpu: "0.5"
            limits:
              memory: "100Mi"
              cpu: "1"